import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import { GameProvider } from "@/contexts/GameContext";
import { ThemeToggle } from "@/components/ThemeToggle";
import Link from "next/link";

const vazirmatn = Vazirmatn({
  variable: "--font-vazirmatn",
  subsets: ["arabic", "latin"],
});

export const metadata: Metadata = {
  title: "بازی جاسوس - Spy Game",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <head>
        <meta
          name="google-site-verification"
          content="lYiZEcAi_DBkCSa1z6VG049H1Xz7xUdxDamnzU2UGPI"
        />
      </head>
      <body className={`${vazirmatn.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <GameProvider>
            <header className="shadow-sm lg:px-0 dark:shadow-neutral-600">
              <div className="container mx-auto flex items-center justify-between p-4">
                <nav className="flex items-center gap-4">
                  <Link href="/" className="font-medium hover:underline">
                    صفحه اصلی
                  </Link>

                  <Link
                    href="https://github.com/iliaAhd/spy-game"
                    className="font-medium hover:underline"
                  >
                    گیت هاب
                  </Link>
                </nav>
                <ThemeToggle />
              </div>
            </header>
            {children}
          </GameProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
